const PENDING = '_PENDING';
const FULFILLED = '_FULFILLED';
const REJECTED = '_REJECTED';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_PENDING = SEARCH_MOVIES + PENDING;
export const SEARCH_MOVIES_FULFILLED = SEARCH_MOVIES + FULFILLED;
export const SEARCH_MOVIES_REJECTED = SEARCH_MOVIES + REJECTED;

export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const CHANGE_SEARCH_BY = 'CHANGE_SEARCH_BY';
export const CHANGE_SORT_BY = 'CHANGE_SORT_BY';

export const LOAD_MOVIE = 'LOAD_MOVIE';
export const LOAD_MOVIE_PENDING = 'LOAD_MOVIE_PENDING';
export const LOAD_MOVIE_FULFILLED = 'LOAD_MOVIE_FULFILLED';
export const LOAD_MOVIE_REJECTED = 'LOAD_MOVIE_REJECTED';

export const LOAD_MOVIES_BY_GENRE = 'LOAD_MOVIES_BY_GENRE';
export const LOAD_MOVIES_BY_GENRE_PENDING = 'LOAD_MOVIES_BY_GENRE_PENDING';
export const LOAD_MOVIES_BY_GENRE_FULFILLED = 'LOAD_MOVIES_BY_GENRE_FULFILLED';
export const LOAD_MOVIES_BY_GENRE_REJECTED = 'LOAD_MOVIES_BY_GENRE_REJECTED';
