const PENDING = '_PENDING';
const FULFILLED = '_FULFILLED';
const REJECTED = '_REJECTED';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_PENDING = SEARCH_MOVIES + PENDING;
export const SEARCH_MOVIES_FULFILLED = SEARCH_MOVIES + FULFILLED;
export const SEARCH_MOVIES_REJECTED = SEARCH_MOVIES + REJECTED;
