const PENDING = '_PENDING';
const FULFILLED = '_FULFILLED';
const REJECTED = '_REJECTED';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_PENDING = SEARCH_MOVIES + PENDING;
export const SEARCH_MOVIES_FULFILLED = SEARCH_MOVIES + FULFILLED;
export const SEARCH_MOVIES_REJECTED = SEARCH_MOVIES + REJECTED;

export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const CHANGE_SEARCH_BY = 'CHANGE_SEARCH_BY';
export const CHANGE_SORT_BY = 'CHANGE_SORT_BY';
